name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.16.3"
      - working-directory: day01
        run: ./test.sh
      - working-directory: day02
        run: ./test.sh
